<?php
/*
 * Functions file
 * Calls all other required files
 * PLEASE DO NOT EDIT THIS FILE IN ANY WAY
 *
 * @package nirvana
 */

// variable for theme version
//
  add_filter('show_admin_bar', '__return_false');

  add_action('widgets_init', 'main_widgets');

    function main_widgets(){
    register_sidebar([
      'name' => 'Центральная часть в шапке',
      'id' => 'sidebar-top-center',
      'before_widget' => '<div class="widget-top-center %2$s">',
      'after_widget'  => "</div>\n"
    ]);
  }


define ('_CRYOUT_THEME_NAME','nirvana');
define ('_CRYOUT_THEME_VERSION','1.4.3');

require_once(get_template_directory() . "/admin/main.php"); // Load necessary admin files

//Loading include files
require_once(get_template_directory() . "/includes/theme-setup.php");     // Setup and init theme
require_once(get_template_directory() . "/includes/theme-styles.php");    // Register and enqeue css styles and scripts
require_once(get_template_directory() . "/includes/theme-loop.php");      // Loop functions
require_once(get_template_directory() . "/includes/theme-meta.php");      // Meta functions
require_once(get_template_directory() . "/includes/theme-comments.php");  // Comment functions
require_once(get_template_directory() . "/includes/theme-functions.php"); // Misc functions
require_once(get_template_directory() . "/includes/theme-hooks.php");     // Hooks
require_once(get_template_directory() . "/includes/widgets.php");     	  // Theme Widgets
require_once(get_template_directory() . "/includes/ajax.php");     	      // Ajax
require_once(get_template_directory() . "/includes/tgm.php");             // TGM Plugin Activation
